// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wavaapdndwjvxylfjvqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhdmFhcGRuZHdqdnh5bGZqdnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNjY4MTEsImV4cCI6MjA3NDk0MjgxMX0.oMgJsYT7UZb3U2a-SuXX0AEU5ZJb7ONeJnRIfi5urlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});